/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package researchknowledgemanager;

/**
 *
 * @author Xable Enterprises
 */
public class UserRepositoryPrompt extends javax.swing.JDialog {

    String userInput;
    boolean successfulExit = false;

    /**
     * Creates new form UserRepositoryPrompt
     */
    public UserRepositoryPrompt(java.awt.Frame parent, boolean modal, String path) {
        super(parent, modal);
        userInput = "";
        initComponents();
        if (path != null) {
            currentRepFolder.setText("Current repository folder path:    " + path);
        } else if (path == null) {
            currentRepFolder.setText("No repository folder specified yet...");
        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserInput = new javax.swing.JTextField();
        javax.swing.JButton SubmitButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        currentRepFolder = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Repository Folder Path?");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        UserInput.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        UserInput.setToolTipText("Filepath of the repository folder. This file path should end in a '\\' such as C:\\My\\Folder\\Path\\");
            UserInput.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    UserInputActionPerformed(evt);
                }
            });

            SubmitButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
            SubmitButton.setText("Submit");
            SubmitButton.setAlignmentX(0.5F);
            SubmitButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    SubmitButtonActionPerformed(evt);
                }
            });

            CancelButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
            CancelButton.setText("Cancel");
            CancelButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    CancelButtonActionPerformed(evt);
                }
            });

            currentRepFolder.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
            currentRepFolder.setText("[Dynamic text that will be changed during runtime]");
            currentRepFolder.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4)));

            jScrollPane2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4)));

            jTextPane1.setEditable(false);
            jTextPane1.setBorder(null);
            jTextPane1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            jTextPane1.setText("The repository folder should be the parent directory which contains all of the files you wish to tag. Specify the repository folder path for the system, then click the \"Submit\" button.\n\nValid Examples:\n- A:\\ \n- B:\\MyFolder\\ \n- C:\\My\\Really\\Extremely\\Long\\Folder\\Path\\Here\\");
                jTextPane1.setOpaque(false);
                jScrollPane2.setViewportView(jTextPane1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(UserInput))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(currentRepFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(currentRepFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UserInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubmitButton)
                            .addComponent(CancelButton))
                        .addGap(6, 6, 6))
                );

                pack();
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void UserInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInputActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed

        successfulExit = false;
        exitPrompt();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        successfulExit = true;
        exitPrompt();
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        exitPrompt();
        userInput = "";
    }//GEN-LAST:event_formWindowClosing

    protected void exitPrompt() {
        userInput = this.UserInput.getText();
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField UserInput;
    private javax.swing.JLabel currentRepFolder;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
